version: "3.9"
services:
  nginx:
    image: "nginx"
    container_name: nginx
    environment:
      - BACKEND_LISTEN_PORT=${BACKEND_LISTEN_PORT}
      - BACKEND_TARGET_CONTAINER=${BACKEND_TARGET_CONTAINER}
      - BACKEND_TARGET_PORT=${BACKEND_TARGET_PORT}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /Users/hacker/WorkSpace/B_Personal/Docker_HealthChecker/nginx/templates:/etc/nginx/templates
      - /Users/hacker/WorkSpace/B_Personal/Docker_HealthChecker/nginx/nginx.conf:/etc/nginx/nginx.conf
# 여기서 /Users/hacker/WorkSpace/B_Personal/Docker_HealthChecker 인 이유는 docker는 host를 공유하기 때문에
# 공유해오는것도 호스트의 파일이다.

  backend_master:
    image: "ilsamhz/multi_mall_back:latest"
    container_name: backend_master
    expose:
      - 8000
    restart: "no"
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/api/v1/common/codes"]
      test: sh -c 'exit 1'
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend_slave:
    image: "ilsamhz/multi_mall_back:latest"
    container_name: backend_slave
    expose:
      - 8000
    restart: "no"
    healthcheck:
      test: sh -c 'curl --fail "http://localhost:8000/api/v1/common/codes" || exit 1'
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend_rollback:
    image: "ilsamhz/multi_mall_back:rollback"
    container_name: backend_rollback
    expose:
      - 8000
    restart: "no"
    healthcheck:
      test: sh -c 'curl --fail "http://localhost:8000/api/v1/common/codes" || exit 1'
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s


  frontend_master:
    image: "ilsamhz/multi_mall_front:latest"
    container_name: frontend_master
    restart: "no"
    expose:
      - 3000
    healthcheck:
      test: sh -c 'curl --fail "http://localhost:3000/" || exit 1'
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend_slave:
    image: "ilsamhz/multi_mall_front:latest"
    container_name: frontend_slave
    restart: "no"
    expose:
      - 3000
    healthcheck:
      test: sh -c 'curl --fail "http://localhost:3000/" || exit 1'
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend_rollback:
    image: "ilsamhz/multi_mall_front:rollback"
    container_name: frontend_rollback
    restart: "no"
    expose:
      - 3000
    healthcheck:
      test: sh -c 'curl --fail "http://localhost:3000/" || exit 1'
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
